<?php
/**
 * contentinum - accessibility websites
 *
 * LICENSE
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @category contentinum user login
 * @package View
 * @author Michael Jochum, michael.jochum@jochum-mediaservices.de
 * @copyright Copyright (c) 2009-2013 jochum-mediaservices, Katja Jochum (http://www.jochum-mediaservices.de)
 * @license http://www.opensource.org/licenses/bsd-license
 * @since contentinum version 5.0
 * @link      https://github.com/Mikel1961/contentinum-components
 * @version   1.0.0
 */
// display form
$aside = '';
$mcontent = '<h1>' . $this->translate('User Login') . '</h1>';
$header = '';
$footer = '';
$this->layoutassets($this->htmllayouts,'login');
$locked = false;
if ($this->messages){
    $str = '';
    if (is_array($this->messages)){
        foreach ($this->messages as $message){
            if ( is_array($message)){
                $str .= implode(' ', $message);
            } else {
                $str .= $message;
            }
        }
    } else {
        $str = $this->messages;
    }
    if ('user_locked' == $str){
        $locked = true;
        $mcontent .= 'User locked due to failed attempt.';
    }
    $mcontent .= '<h4 class="user-error">' . $this->translate($str) . '</h4>';
}
if (false === $locked){
    $mcontent .= $this->renderForm($this->form);
} 
$layout = $this->buildlayout($this->htmllayouts,'login');
foreach ($layout as $row) {
    if (is_array($row)) {
        foreach ($row as $k => $v) {
            switch ($k) {
                case 'assign':
                    $assign = explode(';', $v);
                    foreach ($assign as $value) {
                        if ('header' == $value) {
                            echo "\n" . $header;
                        } elseif ('aside' == $value){
                            echo "\n" . $aside;
                        } elseif ('allcontent' == $value){
                            echo "\n" . $mcontent;
                        } elseif ('footer' == $value){
                            echo "\n" . $footer;
                        } else {
                            echo "\n" . $this->$value;
                        }
                    }
                    break;
                default:
            }
        }
    } else {
        echo "\n" . $row;
    }
}
?>