<?php
/**
 * contentinum - accessibility websites
 *
 * LICENSE
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @category contentinum backend
 * @package View
 * @author Michael Jochum, michael.jochum@jochum-mediaservices.de
 * @copyright Copyright (c) 2009-2013 jochum-mediaservices, Katja Jochum (http://www.jochum-mediaservices.de)
 * @license http://www.opensource.org/licenses/bsd-license
 * @since contentinum version 5.0
 * @link      https://github.com/Mikel1961/contentinum-components
 * @version   1.0.0
 */
use ContentinumComponents\Html\HtmlTable;
use ContentinumComponents\Html\Table\FactoryTable;
// prepare content, create a table
$tableFactory = new HtmlTable(new FactoryTable());
$ctrlpath = 'contribution';
// set table tag attributes
$tableFactory->setAttributes('class', 'table tblNoSort display compact');
$tableFactory->setAttributes('id', 'mcworkTables');
$i = 0;
$iClass = 0;

$headlines = array(
    '#' => array(),
    'Title' => array(),
    'Edit' => array(
        'head' => array(
            'class' => 'hide-for-small text-right'
        ),
        'body' => array(
            'class' => 'hide-for-small text-right'
        )
    )
)
;
$ihead = count($headlines);
foreach ($headlines as $column => $attributes) {
    $columns[] = $this->translate($column);
    if (is_array($attributes) && ! empty($attributes)) {
        foreach ($attributes as $area => $attribute) {
            switch ($area) {
                case 'head':
                    $tableFactory->setHeadlineAttributtes('class', $attribute['class'], $i);
                    break;
                case 'body':
                    $tableFactory->setTagAttributtes('class', $attribute['class'], $i);
                    break;
                default:
                    break;
            }
        }
    }
    $i ++;
}
$tableFactory->setHeadline($columns);
$i = 0;
foreach ($this->entries as $entry) {
    $i ++;
    $rowContent = array();
    $rowContent[] = '<input id="row' . $i . '" type="checkbox" value="' . $entry->id . '" name="cb[]" data-name="' .  $entry->title . '" />';  
    $rowContent[] = $entry->title;

    
    $props = array(
        'edit' => array(
            'href' => '/mcwork/' . $ctrlpath . '/recycle/' . $entry->id,
            'label' => '<i class="fa fa-recycle"></i>',
            'attribs' => array(
                'title' => 'Recycle item',
                'class' => 'button tiny'
            )
        ),
        'delete' => array(
            'href' => '/mcwork/' . $ctrlpath . '/delete/' . $entry->id,
            'attribs' => array(
                'data-name' => $entry->title,
                'data-ident' => 'row' . $i,
                'title' => 'Delete item',
                'class' => 'button tiny alert deleteitem'
            )
        ),
        'info' => array(
            'attribs' => array(
                    'data-service' => 'backend_client_app',
                    'data-appkey' => 'infoapp',
                    'data-upDate' => $entry->upDate->format('d F Y, H:i:s'),
                    'data-registerDate' => $entry->registerDate->format('d F Y, H:i:s'),
                    'data-createBy' => $entry->createdBy,
                    'data-updateBy' => $entry->updateBy,
                    'data-username' => $this->identity->name,
                    'data-role' => $this->role,
                    'title' => 'Item properties',
                    'class' => 'button tiny infotip'
            )
        )
    );    
    if (1 === $entry->id){
        unset($props['delete']);
    }
    $rowContent[] = $this->mcworkToolbar($props, true, $this->tableeditcontent->toArray(), false );
    $tableFactory->setHtmlContent($rowContent);
}
$html = $tableFactory->display();
$html .= $this->translate($this->mcworkContent($this->page, $this->pagecontent, 'content'));
$toolbar = '';
if (isset($this->toolbarcontent)) {
    $links = array(
        'edit' => array(
            'label' => '<i class="fa fa-recycle"></i>',
            'href' => '/mcwork/' . $ctrlpath . '/recycle'
        ),
        'delete' => array(
            'href' => '/mcwork/' . $ctrlpath . '/delete'
        ),
        'back' => array(
            'href' => '/mcwork/' . $ctrlpath
        )        
    );
    $toolbar = $this->mcworkToolbar($links, true, $this->toolbarcontent->toArray());
}
// output, display content
if (isset($this->widget)) {
    $content = str_replace('{TEMPLATE_HEADER}',$this->translate($this->mcworkContent($this->page, $this->pagecontent, 'subheadline')) , $this->widget);
    $content = str_replace('{TEMPLATE_TOOLBAR}', $toolbar, $content);
    echo str_replace('{TEMPLATE_CONTENT}', $html, $content);
} else {
    echo $this->translate($this->mcworkContent($this->page, $this->pagecontent, 'subheadline'));
    echo $html;
}
?>