<?php

echo $this->doctype();
echo "\n<html" . $this->htmlTagAttribs . ">\n";
?>
<head>
<meta charset="utf-8">
<?php
echo $this->headTitle()->setAutoEscape(false) . "\n";
echo $this->headMeta() . "\n";
echo $this->plugin('HeadLink');
echo $this->plugin('HeadStyle');
echo $this->plugin('HeadScript');
?>
</head>
<?php
echo "<body" . $this->bodyTagAttribs . ">";
echo $this->content;
echo $this->plugin('InlineScript');
?>
</body>
</html>