<?php
/**
 * contentinum - accessibility websites
 *
 * LICENSE
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @category contentinum backend
 * @package View
 * @author Michael Jochum, michael.jochum@jochum-mediaservices.de
 * @copyright Copyright (c) 2009-2013 jochum-mediaservices, Katja Jochum (http://www.jochum-mediaservices.de)
 * @license http://www.opensource.org/licenses/bsd-license
 * @since contentinum version 5.0
 * @link      https://github.com/Mikel1961/contentinum-components
 * @version   1.0.0
 */
// add further scripts

if ($this->bodyScriptFiles && is_array($this->bodyScriptFiles)){
    foreach ($this->bodyScriptFiles as $key => $scripts){
        if ('prepend' === $key){
            foreach ($scripts as $script){
                $this->inlinescript()->prependFile($script);
            }
        } else {
            foreach ($scripts as $script){
                $this->inlinescript()->appendFile($script);
            }
        }
    }
}


// display form
$html = $this->renderForm($this->form);
$html .= $this->translate($this->mcworkContent($this->page, $this->pagecontent, 'content'));
$cat = '';
if (false !== $this->category){
    $cat = '/category/' . $this->category;
}

if ( is_array($this->btnconfiguration) ){
    
    $btn = $this->btnconfiguration;
    if (isset($btn['cancel'])){
        $btn['cancel']['attribs']['data-back'] = $this->abortation . $cat; 
    }
    
} else {

    $btn = array(
        'save' => array(),
        'cancel' => array('label' => 'Cancel', 'attribs' => array('data-back' => $this->abortation . $cat )),
    );
}

$button = $this->mcworkToolbar($btn,true,$this->formbuttons->toArray());

if (isset($this->widget)) {
    $content = str_replace('{TEMPLATE_HEADER}', $this->translate($this->mcworkContent($this->page, $this->pagecontent, 'subheadline')) , $this->widget);
    $content = str_replace('{TEMPLATE_TOOLBAR}', $button, $content);
    echo str_replace('{TEMPLATE_CONTENT}', $html, $content);
} else {
    echo $this->translate($this->mcworkContent($this->page, $this->pagecontent, 'subheadline'));
    echo $html;
}
?>