<?php
$groupstyles = $this->groupstyles['styles'];
$htmlwidgets = $this->htmlwidgets['widgets'];
$contentstyles = $this->contentstyles['contribution'];
$content = '';
$html = '';
$it = 1;
foreach ($this->entries as $row){
    if (isset($groupstyles[$row['groupStyle']]) && ($viewHelper = $groupstyles[$row['groupStyle']]->viewhelper) ) {
        $content = $this->$viewHelper($row,$groupstyles[$row['groupStyle']]->toArray(), $this->medias,$contentstyles);
    } else {
        $content = $this->contribution($row,$this->medias,$contentstyles);
    }
    switch ($row['htmlwidgets']){
        case 'none':
            $html[$row['adjustments']][$row['url']][] = $content; 
            break;            
        default:
            $html[$row['adjustments']][$row['url']][] = $this->contentrow( $row,$content,$htmlwidgets );
            break;
    } 
    $it++;
}
$assigns = $this->assigns['assigns'];
$content = array();
foreach ($assigns as $templateKey => $templateAssign){
    if (isset($html[$templateKey]['_default']) ){
        $content[$templateAssign->assign] = implode ( ' ' , $html[$templateKey]['_default']);
    }
    if (isset($html[$templateKey][$this->pageurl]) ){
        if ( isset($content[$templateAssign->assign]) ){
            $content[$templateAssign->assign] .= implode ( ' ' , $html[$templateKey][$this->pageurl] );
        } else {
            $content[$templateAssign->assign] = implode ( ' ' , $html[$templateKey][$this->pageurl] );
        }
    }    
}
$this->layoutassets($this->htmllayouts,$this->templateKey,$this->htmlassets);
$layout = $this->buildlayout($this->htmllayouts,$this->templateKey);
foreach ($layout as $row) {
	if (is_array($row)) {
		foreach ($row as $k => $v) {
			switch ($k) {
				case 'assign':
					$assign = explode(';', $v);
					foreach ($assign as $value) {
					    if ( isset($content[$value]) ){
					        echo "\n" . $content[$value];
						} else {
							echo "\n" . $this->$value;
						}
					}
					break;
				default:
			}
		}
	} else {
		echo "\n" . $row;
	}
}
?>