<?php
use ContentinumComponents\Tools\HandleSerializeDatabase;
/**
 * contentinum - accessibility websites
*
* LICENSE
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
* ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
* LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
* CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
		* SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
		* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
* CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*
* @category contentinum backend
* @package View
* @author Michael Jochum, michael.jochum@jochum-mediaservices.de
* @copyright Copyright (c) 2009-2013 jochum-mediaservices, Katja Jochum (http://www.jochum-mediaservices.de)
* @license http://www.opensource.org/licenses/bsd-license
* @since contentinum version 5.0
* @link      https://github.com/Mikel1961/contentinum-components
* @version   1.0.0
*/
$mcUnserialize = new HandleSerializeDatabase();
?>
<div id="main"><ul id="tiles">
<?php
foreach ($this->entries as $entry){
    if ('_nomedia' != $entry->mediaType && 0 == $entry->parentMedia && 'index' == $entry->resource){    

        
        if ( preg_match('/image\//', $entry->mediaType)  ){
            $editApp = 'imageattribute';
            $img = '<img src="' . $entry->mediaLink . '" alt="'. $entry->mediaName .'" />';
        } else {
            $editApp = 'fileattribute';
            switch ($entry->mediaType){
                case 'application/pdf' :
                    $img ='<p><i class="fa fa-file-pdf-o fa-5x pdf-color"></i></p>';
                    break;
                default:
                    $img = '<p><i class="fa fa-file fa-5x"></i></p>';
                    break;
        
            }
        }
        $data = ' data-service="backend_client_app" data-appkey="'.$editApp.'" data-ident="'.$entry->id.'"'; 
        echo '<li><a class="loadedititem editapp" href="#"'.$data.'>' . $img;
        echo '<p>' . $entry->mediaName . '</p></a></li>';
    }
}



?>
</ul></div>